name: Test action
on: [push]

jobs:
  test-action:
    name: Run
    runs-on: ubuntu-latest

    steps:

    - name: Create cluster
      uses: efcloud/gh-actions-kind-env@master
      with:
        kind-version: "v0.5.1"
        kubefwd-version: "v1.9.2"
        bepatient-version: "v0.1.0"

    - name: Verify results
      run: |
        echo "-------kind version----------------"
        kind version

        echo "-------kubectl config view----------------"
        kubectl config view

        echo "-------kubectl config current-context----------------"
        kubectl config current-context

        echo "-------kubectl create ns itest---------------"
        kubectl create ns itest

        echo "-------kubectl get ns---------------"
        kubectl get ns

        echo "-------kubefwd version----------------"
        kubefwd version

        echo "-------bepatient version----------------"
        bepatient version